name: build

on:
  push:
    branches: ["main"]

  pull_request:
  workflow_call:
    outputs:
      binaries:
        description: "Linux, MacOS and Windows binaries"
        value: ${{jobs.build.outputs.artifact}}
permissions:
  id-token: write
  contents: read
  attestations: write
jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{steps.upload.outputs.artifact-url}}
    steps:
      - uses: actions/checkout@v4
      - run: |
          bazel build //:for_all_platforms
          mv bazel-out/macos_aarch64-opt/bin/external/libarchive+/tar/bsdtar tar_darwin_arm64
          mv bazel-out/macos_x86_64-opt/bin/external/libarchive+/tar/bsdtar tar_darwin_amd64
          mv bazel-out/linux_aarch64_musl-opt/bin/external/libarchive+/tar/bsdtar tar_linux_arm64
          mv bazel-out/linux_x86_64_musl-opt/bin/external/libarchive+/tar/bsdtar tar_linux_amd64
          mv bazel-out/windows_x86_64-opt/bin/external/libarchive+/tar/bsdtar.exe tar_windows_x86_64.exe
          mv bazel-out/windows_aarch64-opt/bin/external/libarchive+/tar/bsdtar.exe tar_windows_arm64.exe
      - uses: actions/attest-build-provenance@v4
        with:
          subject-path: 'tar_*'
      - uses: actions/upload-artifact@v4
        id: upload
        with:
          name: binaries
          retention-days: 1
          path: |
            tar_darwin_arm64
            tar_darwin_amd64
            tar_linux_arm64
            tar_linux_amd64
            tar_windows_arm64.exe
            tar_windows_x86_64.exe
